export default {
  CREATE_USER: 'CREATE_USER',
  AUTH_USER: 'AUTH_USER',
  UPDATE_USER: 'UPDATE_USER',
  GET_USER: 'GET_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  RESET_USER_PASSWORD: 'RESET_USER_PASSWORD',
};
